[tool.poetry]
name = "pdm-converter"
version = "0.1.0"
description = "A decimal-to-binary number converter"
authors = ["Juno Takano <juno.takano@aluno.ifsp.edu.br>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11.6"
flet = "^0.23.2"
